name: Tito Ayudantito
on: #pull_request
  push:
      branches:
        - tito-ayudantito

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run HTML/CSS analysis
        uses: Compu3Unla/tito-ayudantito@v1
        with:
          path: "."          # folder to scan, default "."
          fail-on: "error"    # "error" or "warning", default "error"
          lang: "es"          # translation table locale, default "es"
